//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProdNet.Modals
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aspet_devEntities : DbContext
    {
        public aspet_devEntities()
            : base(ConfigurationManager.AppSettings["EnvEF"].ToString())
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<DailyQtyComplaintRpt> DailyQtyComplaintRpts { get; set; }
        public virtual DbSet<DailyWeight> DailyWeights { get; set; }
        public virtual DbSet<DefectCode> DefectCodes { get; set; }
        public virtual DbSet<DWCavity> DWCavities { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<LogSheet> LogSheets { get; set; }
        public virtual DbSet<Machinery> Machineries { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<MaterialEntry> MaterialEntries { get; set; }
        public virtual DbSet<MaterialOther> MaterialOthers { get; set; }
        public virtual DbSet<PackingMaterial> PackingMaterials { get; set; }
        public virtual DbSet<PDCavity> PDCavities { get; set; }
        public virtual DbSet<PhysicalReport> PhysicalReports { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<ProdHandling> ProdHandlings { get; set; }
        public virtual DbSet<ProdLog> ProdLogs { get; set; }
        public virtual DbSet<Production> Productions { get; set; }
        public virtual DbSet<RawMaterial> RawMaterials { get; set; }
        public virtual DbSet<ReportCavity> ReportCavities { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<ResinMoistrRpt> ResinMoistrRpts { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<station> stations { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<truck> trucks { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<VCavity> VCavities { get; set; }
        public virtual DbSet<VisualReport> VisualReports { get; set; }
        public virtual DbSet<BagConsumption> BagConsumptions { get; set; }
    }
}
