//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProdNet.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class BagConsumption
    {
        public int wBagId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string sMaterial { get; set; }
        public Nullable<int> wMaterialId { get; set; }
        public Nullable<int> wShift { get; set; }
        public Nullable<int> wShiftUserId { get; set; }
        public Nullable<int> wCheckedBy { get; set; }
        public Nullable<int> wOperator { get; set; }
        public string sType { get; set; }
        public Nullable<int> MachineNo { get; set; }
    }
}
