//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProdNet.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyQtyComplaintRpt
    {
        public int wQtyComplantId { get; set; }
        public Nullable<int> wShiftId { get; set; }
        public string sShift { get; set; }
        public Nullable<int> wMCno { get; set; }
        public string Product { get; set; }
        public string Weight { get; set; }
        public string color { get; set; }
        public string Troubles { get; set; }
        public Nullable<int> CheckBy { get; set; }
        public string ReportingTo { get; set; }
        public Nullable<System.DateTime> ReportingTime { get; set; }
        public Nullable<int> wInspectedId { get; set; }
        public Nullable<System.DateTime> solvedTime { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> wDateTime { get; set; }
        public string sRemarks { get; set; }
    }
}
