//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProdNet.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyWeight
    {
        public int wDWId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string sProduct { get; set; }
        public string colour { get; set; }
        public Nullable<int> ACheckedBy { get; set; }
        public Nullable<int> BCheckedBy { get; set; }
        public Nullable<int> CCheckedBy { get; set; }
    }
}
