//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProdNet.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class DWCavity
    {
        public int wCavityId { get; set; }
        public Nullable<int> wCavityNo { get; set; }
        public Nullable<int> wDWId { get; set; }
        public Nullable<int> AWeight { get; set; }
        public Nullable<int> BWeight { get; set; }
        public Nullable<int> CWeight { get; set; }
    }
}
