//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProdNet.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogSheet
    {
        public int wSheeetId { get; set; }
        public Nullable<int> wLogId { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string RegretionR { get; set; }
        public string RegrationL { get; set; }
        public string ProcessS { get; set; }
        public string ProcessA { get; set; }
        public string DewS { get; set; }
        public string DewA { get; set; }
        public string DHDewS { get; set; }
        public string DHDewA { get; set; }
        public string PressureIn { get; set; }
        public string PressureOUT { get; set; }
        public string PressureLp { get; set; }
        public string PressureHp { get; set; }
        public string CoolingTemp { get; set; }
        public string ACPressureLOad { get; set; }
        public string ACPressureUnload { get; set; }
        public string CTPTExmo { get; set; }
        public string CTPBar { get; set; }
        public string PhaseVolts { get; set; }
        public string ShoutConter { get; set; }
        public string Quality { get; set; }
        public Nullable<int> Operator { get; set; }
    }
}
