//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProdNet.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialEntry
    {
        public int wMaterialId { get; set; }
        public Nullable<int> wTruckId { get; set; }
        public Nullable<int> wMaterial { get; set; }
        public string sCompany { get; set; }
        public Nullable<int> wOwnType { get; set; }
        public string sName { get; set; }
        public string sGrade { get; set; }
        public string sChalan { get; set; }
        public string sIDNO { get; set; }
        public Nullable<System.DateTime> dRentFrom { get; set; }
        public Nullable<System.DateTime> dRentTo { get; set; }
        public string sQuantity { get; set; }
        public string sTotal { get; set; }
        public string sWareHouse { get; set; }
        public string sVisualCheck { get; set; }
        public string sRemark { get; set; }
        public Nullable<int> wSupplierId { get; set; }
        public Nullable<int> wMaterialType { get; set; }
    }
}
