//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProdNet.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialOther
    {
        public int wOtherId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<int> wSupplierId { get; set; }
        public string TruckNo { get; set; }
        public Nullable<int> Quatity { get; set; }
        public string QType { get; set; }
        public string ChalanNo { get; set; }
        public Nullable<int> CheckBy { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> wDateTime { get; set; }
        public string Stores { get; set; }
        public Nullable<int> Weight { get; set; }
    }
}
