//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProdNet.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackingMaterial
    {
        public int wPackingId { get; set; }
        public string sType { get; set; }
        public string AccountOf { get; set; }
        public string MaterialType { get; set; }
        public Nullable<int> SuplierId { get; set; }
        public string TruckNo { get; set; }
        public Nullable<int> Quatity { get; set; }
        public string QType { get; set; }
        public Nullable<int> Weight { get; set; }
        public string WareHouse { get; set; }
        public string ChalanNo { get; set; }
        public Nullable<int> CheckBy { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime wDateTime { get; set; }
    }
}
