//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProdNet.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDCavity
    {
        public int wPhyCavityId { get; set; }
        public Nullable<int> wPhyDimId { get; set; }
        public Nullable<int> DimWeight { get; set; }
        public string NeckId { get; set; }
        public string TOTHeight { get; set; }
        public string NeckOd { get; set; }
        public string BodyDia { get; set; }
        public string Bend { get; set; }
        public string WallThickness { get; set; }
        public string PolariseLight { get; set; }
        public Nullable<int> wCavityNo { get; set; }
    }
}
