//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProdNet.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalReport
    {
        public int wPhyDimId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> wMCNo { get; set; }
        public string wPerSize { get; set; }
        public Nullable<int> wShiftID { get; set; }
        public Nullable<int> wMouldNo { get; set; }
    }
}
