//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProdNet.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public int wPosId { get; set; }
        public string Position1 { get; set; }
        public string sExtra { get; set; }
    }
}
