//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProdNet.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public int wProductionId { get; set; }
        public Nullable<int> wMaterialId { get; set; }
        public Nullable<int> wIdNO { get; set; }
        public Nullable<System.DateTime> wDate { get; set; }
        public string sSize { get; set; }
        public string sGrade { get; set; }
        public string M1rejection { get; set; }
        public string M1Lumps { get; set; }
        public string M2rejection { get; set; }
        public string M2Lumps { get; set; }
        public Nullable<int> wPrepairedBy { get; set; }
        public Nullable<int> wReceivedBy { get; set; }
    }
}
