//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProdNet.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdLog
    {
        public int wLogId { get; set; }
        public Nullable<int> wProductionId { get; set; }
        public Nullable<System.DateTime> wLogDate { get; set; }
        public string MachineHpte { get; set; }
        public string partWt { get; set; }
        public string sShift { get; set; }
        public string CycleTime { get; set; }
        public string PerformAvg { get; set; }
        public string ProdKg { get; set; }
        public string Rejection { get; set; }
        public string Lumps { get; set; }
        public string PetMaterial { get; set; }
        public Nullable<System.DateTime> DownTime { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public string ColTDS { get; set; }
        public string ColPH { get; set; }
        public string ColTemp { get; set; }
        public string Plant { get; set; }
        public string Temprature { get; set; }
        public string Humidity { get; set; }
        public string sRemarks { get; set; }
        public Nullable<int> wShiftIncharge { get; set; }
        public Nullable<int> wManager { get; set; }
    }
}
