//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProdNet.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdHandling
    {
        public int wHandlingId { get; set; }
        public Nullable<int> wProductionId { get; set; }
        public Nullable<int> wBoxes { get; set; }
        public Nullable<int> wTransferBoxes { get; set; }
        public Nullable<int> wGoods { get; set; }
        public Nullable<System.DateTime> dManufDate { get; set; }
    }
}
