//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProdNet.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int wReportId { get; set; }
        public string MC { get; set; }
        public string Product { get; set; }
        public Nullable<int> wProductionId { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<int> MouldID { get; set; }
        public string PreformSize { get; set; }
        public string colour { get; set; }
        public string sExtra { get; set; }
        public Nullable<int> wDefectCodeId { get; set; }
        public Nullable<int> InspectedBy { get; set; }
        public string Remarks { get; set; }
    }
}
