//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProdNet.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResinMoistrRpt
    {
        public int wRsinRptId { get; set; }
        public Nullable<int> resinBagNo { get; set; }
        public string resinGrade { get; set; }
        public string InvoiceNo { get; set; }
        public string machineNo { get; set; }
        public string Specification { get; set; }
        public string Result { get; set; }
        public Nullable<int> CheckBy { get; set; }
        public string freqPerLot { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> wDateTime { get; set; }
    }
}
