//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProdNet.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int wStockId { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Particulares { get; set; }
        public Nullable<int> HPN { get; set; }
        public string Locker { get; set; }
        public string BoxNo { get; set; }
        public string Qty { get; set; }
        public string Remarks { get; set; }
    }
}
