//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProdNet.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class truck
    {
        public int wTruckId { get; set; }
        public string wTruckNo { get; set; }
        public Nullable<int> wContainerNo { get; set; }
        public Nullable<int> wSealNo { get; set; }
        public string sBrandName { get; set; }
        public string sQuantity { get; set; }
        public Nullable<int> wStationId { get; set; }
        public Nullable<int> wUserId { get; set; }
        public string sdesc { get; set; }
        public string sExt { get; set; }
        public Nullable<System.DateTime> vdate { get; set; }
    }
}
