//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProdNet.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int wUserId { get; set; }
        public string sUser { get; set; }
        public string sPassword { get; set; }
        public int wRoleId { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string sEmail { get; set; }
        public string sNotes { get; set; }
        public string Contact { get; set; }
    }
}
