//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProdNet.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCavity
    {
        public int wVCavityId { get; set; }
        public Nullable<int> wVCavityNo { get; set; }
        public string sStatus1 { get; set; }
        public string sStatus2 { get; set; }
        public Nullable<int> wVisualId { get; set; }
        public Nullable<int> wDefectCodeId { get; set; }
    }
}
