//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspProdNet.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisualReport
    {
        public int wVisualId { get; set; }
        public Nullable<int> wMCno { get; set; }
        public string sProduct { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> wShiftId { get; set; }
        public Nullable<int> wDefectCodeId { get; set; }
        public Nullable<int> wInspectedId { get; set; }
        public string sNotes { get; set; }
    }
}
